filter:
    paths:
        - 'src/*'
before_commands:
    - 'composer install'
tools:
    php_mess_detector:
        config:
            code_size_rules: { npath_complexity: false, excessive_method_length: false }
    php_code_sniffer:
        config:
            standard: PSR1
    php_code_coverage:
        config_path: app/
    php_pdepend: true