filter:
    paths:
        - 'src/*'
before_commands:
    - 'composer install'
tools:
    php_mess_detector:
        config:
            # Satisfy the longer execute()-methods for commands, which tend to decrease readability
            code_size_rules: { excessive_method_length: false, too_many_methods: false }
    php_code_sniffer:
        config:
            standard: PSR1
    php_code_coverage:
        enabled: true
        test_command: phpunit -c app/
    php_pdepend: true
