filter:
    paths:
        - 'src/*'
before_commands:
    - 'cp app/config/parameters.yml.dist app/config/parameters.yml'
    - 'composer install'
tools:
    php_mess_detector: true
    external_code_coverage: true
    php_code_sniffer:
        config:
            standard: PSR1