#!/usr/bin/env php
<?php
/**
 * This file is part of the DEVR CLI-script
 *
 * @author Cas Leentfaar
 * @license http://github.com/cleentfaar/devr
 */
set_time_limit(0);

require_once(__DIR__ . "/app/bootstrapper.php");

use Cleentfaar\Devr\Console\Application;

$application = new Application();
$application->run();
